name: Run ollama server
description: Run an ollama server with the model you provide

inputs:
  model:
    description: The model to run

runs:
  using: composite
  steps:
    - id: cache-ollama-install
      uses: actions/cache@v4
      with:
        path: ./ollama-run
        key: ollama-${{ hashFiles('install-ollama.sh') }}

    - uses: actions/cache@v4
      with:
        path: ~/.ollama
        key: ollama-models

    - if: steps.cache-ollama-install.outputs.cache-hit != 'true'
      run: ./install-ollama.sh
      shell: bash

    - run: echo $(pwd)/ollama-run/bin >> $GITHUB_PATH
      shell: bash

    - run: ollama start &
      shell: bash

    - run: ollama --version
      shell: bash

    - run: ollama pull ${{ inputs.model }}
      shell: bash
