name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --verbose

  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          model: qwen:0.5b
