name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          model: qwen:0.5b
          cache-key: v2

      - run: ollama list
      - run: ollama run qwen:0.5b 'What is the capital of France?'
